export const STADIUM_ZONES_METADATA: Record<string, { label: string; type: string; location: [number, number] }> = {
  gate_north: { label: "North Gate", type: "entrance", location: [400, 100] },
  gate_south: { label: "South Gate", type: "entrance", location: [400, 700] },
  gate_east: { label: "East Gate", type: "entrance", location: [700, 400] },
  gate_west: { label: "West Gate", type: "entrance", location: [100, 400] },
  section_a: { label: "Section A", type: "seating", location: [300, 200] },
  section_b: { label: "Section B", type: "seating", location: [500, 200] },
  section_c: { label: "Section C", type: "seating", location: [300, 600] },
  section_d: { label: "Section D", type: "seating", location: [500, 600] },
  food_court_a: { label: "Food Court A", type: "food", location: [200, 300] },
  food_court_b: { label: "Food Court B", type: "food", location: [600, 300] },
  food_court_c: { label: "Food Court C", type: "food", location: [200, 500] },
  food_court_d: { label: "Food Court D", type: "food", location: [600, 500] },
  wc_north: { label: "Restroom North", type: "wc", location: [350, 150] },
  wc_south: { label: "Restroom South", type: "wc", location: [450, 650] },
  medical_center: { label: "Medical Center", type: "medical", location: [100, 200] },
  exit_main: { label: "Main Exit", type: "exit", location: [400, 750] },
  exit_emergency: { label: "Emergency Exit", type: "exit", location: [750, 400] },
};
